package com.lc.pojo;
// Generated 2019-12-17 16:35:30 by Hibernate Tools 4.3.5.Final

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer uid;
	private String uname;
	private String upwd;

	public Users() {
	}

	public Users(String uname, String upwd) {
		this.uname = uname;
		this.upwd = upwd;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public String getUpwd() {
		return this.upwd;
	}

	public void setUpwd(String upwd) {
		this.upwd = upwd;
	}

}
